# Generated by Django 5.1.6 on 2025-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('N', 'Новость'), ('A', 'Статья')], max_length=1),
        ),
    ]
